### ISSUE TITLE
Expand visible-bitrate with bitdepth,samplerate and channels.

### ISSUE THREAD

**Issue by critkitten** [MusicPlayerDaemon/ncmpc#120]
We have [visible-bitrate](https://github.com/MusicPlayerDaemon/ncmpc/search?q=visible-bitrate), but bitdepth, channels and samplerate are not. 

If implementation is planned, it would be nice if all of three are combined (bitrate,bitdepth,samplerate and channels). 
Replace visible-bitrate with visible-audio(information/specs) or every value deserve it's option.

Every valid audio file should have all four of it.

**Comment by MaxKellermann** [comment]
Do you mean the audio format currently used by MPD, or the audio format of a song file?

**Comment by critkitten** [comment]
if im right the current "visible-bitrate" is current bitrate from played file by mpd updated every x seconds. so same should be valid for bitdepth,channels,samplerate ?  nobody is helped if we display the file values (24bit) but we replay it 16bit.

**Comment by ferdnyc** [comment]
@critkitten Bitrate can _change_ during the course of a song's playback, though (for VBR files) — that's why it's updated periodically. The other three values don't (can't) EVER change while the song is playing, so it's a bit foolish to keep regularly updating them as if they could.

**Comment by MaxKellermann** [comment]
I don't believe that this should be displayed so prominently, but I would be willing accept a PR implementing such an option. Though I wouldn't spend my own time implementing it.

**Comment by critkitten** [comment]
I must admit it would be "nice" but certainly not necessary, perhaps also because it is too complicated for what it demands. 
It is probably better to sort the music into folders properly instead of relying on the player for the information bit depth,channels and sample rate. 

The question that then arises is as you already correctly asked: where do we take the information? alsa or file.

@ferdnyc that makes sense.
