### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by ferdnyc** [MusicPlayerDaemon/ncmpc#121]
I just noticed how many commits there have been to the repo since 0.47 was tagged. They seem to have slowed down, now... maybe it's time to push 0.48 out the door?

**Comment by MaxKellermann** [comment]
There were a few commits but not many user-visible changes, that's why I did not decide to do a release. I wish there were more user-visible changes, but my time is a bit scarce right now ...

**Comment by ferdnyc** [comment]
@MaxKellermann Makes sense. Still, the 7 months' worth of updated translations alone... (Including Korean going to 100% translated, and a full set of all-new Turkish translations. The weblate crowd has been busy!) :grin:

**Comment by MaxKellermann** [comment]
0bcbedb124029c1a206684b7b28ee572615eb96e

**Comment by ferdnyc** [comment]
Builds now in the pipeline for Fedora [rawhide](https://koji.fedoraproject.org/koji/taskinfo?taskID=99689150) and [38](https://koji.fedoraproject.org/koji/taskinfo?taskID=99689164)!
