### ISSUE TITLE
Support venv python in lyric scripts

### ISSUE THREAD

**Issue by lunasophia** [MusicPlayerDaemon/ncmpc#127]
All the lyrics scripts use the shebang `#!/usr/bin/python3`, which means that users who have venvs set up (or just prefer some other `python3`) can't use the scripts without modifying them. As they're typically installed to `$PREFIX/lib` (e.g. `/usr/lib`), this means modifying system files installed by a package manager, which can cause problems with uninstalling / updating.

A more elegant approach is to change the shebang to `#!/usr/bin/env python3`, which will use the first `python3` on the user's `$PATH`. If they have a venv setup, it'll use that `python3`; otherwise, it transparently falls back to the system `python3`.

This does mean that, if a user has a venv setup, they'll need to install the script dependencies (e.g. bs4, requests) into that venv, but even this isn't an insurmountable problem: a user can simply run ncmpc with `env PATH=[$PATH without the venv path] ncmpc` to fall back to the system `python3` (which presumably has the required modules installed via package manager dependency management), and it's easy enough to set this as an alias in their shell rc file.

I can't think of any downsides for this change; it seems to be a strict improvement over what we have today.

**Comment by MaxKellermann** [comment]
Agree. The only downside is a tiny amount of overhead, but that's fine. Why don't you submit a PR?

**Comment by MaxKellermann** [comment]
7c6e17be5e0d3621720d2a9be63d8aa80dc4f072
