### ISSUE TITLE
IPv4Address.hxx: error: 'u_int32_t' was not declared in this scope; did you mean 'uint32_t'?

### ISSUE THREAD

**Issue by barracuda156** [MusicPlayerDaemon/ncmpc#130]
```
[35/127] /opt/local/bin/g++-mp-12 -Isrc/net/libnet.a.p -Isrc/net -I../ncmpc-0.49/src/net -Isrc -I../ncmpc-0.49/src -I. -I../ncmpc-0.49 -I/opt/local/libexec/boost/1.76/include -I/opt/local/include -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++2a -O0 -g -Wcast-qual -Wcast-align -Wdouble-promotion -Wmissing-declarations -Wmissing-format-attribute -Wmissing-noreturn -Wredundant-decls -Wshadow -Wundef -Wvla -Wwrite-strings -fno-threadsafe-statics -fmerge-all-constants -Wno-non-virtual-dtor -Wno-format-truncation -D_GNU_SOURCE -fvisibility=hidden -pipe -Os -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc -MD -MQ src/net/libnet.a.p/IPv6Address.cxx.o -MF src/net/libnet.a.p/IPv6Address.cxx.o.d -o src/net/libnet.a.p/IPv6Address.cxx.o -c ../ncmpc-0.49/src/net/IPv6Address.cxx
FAILED: src/net/libnet.a.p/IPv6Address.cxx.o 
/opt/local/bin/g++-mp-12 -Isrc/net/libnet.a.p -Isrc/net -I../ncmpc-0.49/src/net -Isrc -I../ncmpc-0.49/src -I. -I../ncmpc-0.49 -I/opt/local/libexec/boost/1.76/include -I/opt/local/include -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++2a -O0 -g -Wcast-qual -Wcast-align -Wdouble-promotion -Wmissing-declarations -Wmissing-format-attribute -Wmissing-noreturn -Wredundant-decls -Wshadow -Wundef -Wvla -Wwrite-strings -fno-threadsafe-statics -fmerge-all-constants -Wno-non-virtual-dtor -Wno-format-truncation -D_GNU_SOURCE -fvisibility=hidden -pipe -Os -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc -MD -MQ src/net/libnet.a.p/IPv6Address.cxx.o -MF src/net/libnet.a.p/IPv6Address.cxx.o.d -o src/net/libnet.a.p/IPv6Address.cxx.o -c ../ncmpc-0.49/src/net/IPv6Address.cxx
In file included from ../ncmpc-0.49/src/net/IPv6Address.hxx:16,
                 from ../ncmpc-0.49/src/net/IPv6Address.cxx:4:
../ncmpc-0.49/src/net/IPv4Address.hxx: In constructor 'constexpr IPv4Address::IPv4Address(uint16_t)':
../ncmpc-0.49/src/net/IPv4Address.hxx:112:46: error: 'u_int32_t' was not declared in this scope; did you mean 'uint32_t'?
  112 |                 :IPv4Address(ConstructInAddr(INADDR_ANY), port) {}
      |                                              ^~~~~~~~~~
../ncmpc-0.49/src/net/IPv4Address.hxx: In static member function 'static constexpr in_addr IPv4Address::Loopback()':
../ncmpc-0.49/src/net/IPv4Address.hxx:121:40: error: 'u_int32_t' was not declared in this scope; did you mean 'uint32_t'?
  121 |                 return ConstructInAddr(INADDR_LOOPBACK);
      |                                        ^~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

**Comment by MaxKellermann** [comment]
I don't get it. Why is it missing? ncmpc doesn't use it - it looks like the macOS implementation of the `INADDR_ANY` macro uses it. If macOS uses this non-existing type, then the bug is in macOS, isn't it?

**Comment by MaxKellermann** [comment]
Anyway, what is `/opt/local/bin/g++-mp-12`? This looks like you brought a custom toolchain to your Mac. And maybe it's just your toolchain that is broken. Because the GitHub CI job for macOS is fine, ncmpc is all green.

**Comment by barracuda156** [comment]
@MaxKellermann I am not making a claim whose bug is this, but the error is these, and we have a fix for it.

Our CI now pass: https://github.com/macports/macports-ports/pull/19982

**Comment by barracuda156** [comment]
> Anyway, what is `/opt/local/bin/g++-mp-12`?

Macports GCC.

> This looks like you brought a custom toolchain to your Mac.

Any toolchain is ”custom” – one must build it with some settings. But our settings are transparent: you may take a look, and point to an error, if there is any.

> Because the GitHub CI job for macOS is fine, ncmpc is all green.

GitHub CI for how many MacOS versions? )

**Comment by MaxKellermann** [comment]
Your error message is enough to look at to prove that your toolchain is broken. Your toolchain defines `INADDR_ANY` in a way that it uses the non-standard type `u_int32_t` without however ensuring that the type exists. Your PR suggests to add a workaround to ncmpc instead of fixing the broken toolchain. I don't like that.

**Comment by barracuda156** [comment]
Toolchain does not define random types. Wherever the error comes from, it is not GCC (also we do not have any custom GCC headers).

**Comment by MaxKellermann** [comment]
Let's not get into a discussion of what the term "toolchain" means. Whoever (and whatever you call that entity) defines `INADDR_ANY` using `u_int32_t` needs to ensure that `u_int32_t` exists. This definition is somewhere on your computer, and it's obviously broken.

**Comment by barracuda156** [comment]
> Let's not get into a discussion of what the term "toolchain" means. Whoever (and whatever you call that entity) defines `INADDR_ANY` using `u_int32_t` needs to ensure that `u_int32_t` exists. This definition is somewhere on your computer, and it's obviously broken.

It is not impossible that it is a bug in Apple headers. I am off the desktop, I can find it tomorrow with BBEdit.
However, what is more important: better code with better compatibility which more people can benefit from or proving that Apple did something wrong in a particular OS?

**Comment by MaxKellermann** [comment]
Compatibility with broken systems is a bottomless pit and only reduces the pressure on others to fix those breakages.
Your rhethoric question is not useful for finding a decision because it already implies that adding tons of obscure workarounds for broken systems equals "better code", which I disagree with.
If you have a broken system and don't want to fix it, you know how to work around it.

This discussion doesn't seem productive, so let's stop here.

**Comment by barracuda156** [comment]
> adding tons of obscure workarounds

Well, of the said tons one was a fix for a incorrect workaround added here in an earlier commit, another being pointing out that another commit which removed, again, your existing workarounds, breaks builds on macOS with standard compiler.
Of the three only one potentially qualifies for being obscure.

But I got your point. Anything can be broken apart from what has been committed here. Well, good luck with such an approach.
