### ISSUE TITLE
failed to build 0.50 release on ventura

### ISSUE THREAD

**Issue by chenrui333** [MusicPlayerDaemon/ncmpc#150]
seeing the following build failure while building for ventura

```
  In file included from ../src/event/TimerList.cxx:5:
  ../src/event/TimerList.hxx:22:5: error: constraints not satisfied for class template 'IntrusiveTreeSetOperators' [with T = FineTimerEvent, GetKey = TimerList::GetDue, Compare = std::compare_three_way]
                           IntrusiveTreeSetOperators<FineTimerEvent, GetDue>> timers;
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ../src/util/IntrusiveTreeSet.hxx:139:3: note: because 'std::regular_invocable<std::compare_three_way, std::invoke_result_t<GetDue, const FineTimerEvent &>, std::invoke_result_t<GetDue, const FineTimerEvent &> >' evaluated to false
           std::regular_invocable<std::invoke_result_t<GetKey, const T &>,
           ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/__concepts/invocable.h:35:29: note: because 'invocable<std::compare_three_way, std::chrono::time_point<std::chrono::steady_clock, std::chrono::duration<long long, std::ratio<1, 1000000000> > >, std::chrono::time_point<std::chrono::steady_clock, std::chrono::duration<long long, std::ratio<1, 1000000000> > > >' evaluated to false
  concept regular_invocable = invocable<_Fn, _Args...>;
                              ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/__concepts/invocable.h:29:3: note: because 'std::invoke(std::forward<_Fn>(__fn), std::forward<_Args>(__args)...)' would be invalid: no matching function for call to 'invoke'
    _VSTD::invoke(_VSTD::forward<_Fn>(__fn), _VSTD::forward<_Args>(__args)...); // not required to be equality preserving
    ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/c++/v1/__config:695:17: note: expanded from macro '_VSTD'
  #  define _VSTD std
                  ^
  1 error generated.
```

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/10909929153/job/30279464670?pr=190979
relates to https://github.com/Homebrew/homebrew-core/pull/190979

**Comment by chenrui333** [comment]
cc @MaxKellermann

**Comment by MaxKellermann** [comment]
This looks like a bug in your C++ standard library implementation. Old clang/libc++ are known to be buggy. What are you using?

**Comment by chenrui333** [comment]
it is using clang 1500/xcode 15.2

**Comment by MaxKellermann** [comment]
But what upstream clang/libc++ version is that?

ncmpc builds fine on GH actions, macos-latest, clang 15.0.0, e.g.: https://github.com/MusicPlayerDaemon/ncmpc/actions/runs/10871972077/job/30166446936 - is that the same version you're using? You said clang 1500, but do you really mean 15.0.0? What's the relevant difference between your setup and the one on GH actions?

I believe ncmpc's code is correct, and your toolchain is buggy. If that turns out to be true (and nobody has challenged that), there's nothing I can do to help. I do not support buggy toolchains.

**Comment by chenrui333** [comment]
> But what upstream clang/libc++ version is that?
> 
> ncmpc builds fine on GH actions, macos-latest, clang 15.0.0, e.g.: https://github.com/MusicPlayerDaemon/ncmpc/actions/runs/10871972077/job/30166446936 - is that the same version you're using? You said clang 1500, but do you really mean 15.0.0? What's the relevant difference between your setup and the one on GH actions?
> 
> I believe ncmpc's code is correct, and your toolchain is buggy. If that turns out to be true (and nobody has challenged that), there's nothing I can do to help. I do not support buggy toolchains.

I can see the clang version is the same, but not the xcode sdks (it might be better to add macos-12 to the CI to see if it is reproducible if you dont mind)

**Comment by MaxKellermann** [comment]
It would be okay for me to add macos-12 to the CI, but only if macos-12 has a non-buggy toolchain. If it turns out that the macos-12 toolchain is broken, then ncmpc will not be supported on that OS (at least not with Apple's stock toolchain). As I said, I don't support known-buggy toolchains.
ncmpc requires a C++20 compiler, and you don't have one.

**Comment by chenrui333** [comment]
updating to the latest llvm 19 fixed my issue, gonna ship via https://github.com/Homebrew/homebrew-core/pull/191659

**Comment by chenrui333** [comment]
> It would be okay for me to add macos-12 to the CI, but only if macos-12 has a non-buggy toolchain. 

the builtin toolchain does not work for the build anymore (in this case, it would be macos-13, I would imagine macos-12 would be the same)

**Comment by MaxKellermann** [comment]
Hooray, thanks for confirming.

**Comment by landryb** [comment]
Hi, fwiw i'm facing the same build failure on OpenBSD -current, be it with llvm 16 or 17, and with `std=c++2a` in the build flags. So technically when you say "broken toolchains" you mean "old libc++" ?

**Comment by MaxKellermann** [comment]
> So technically when you say "broken toolchains" you mean "old libc++" ?

No, I don't mean that. I have no idea which version of libc++ you have, and whether a different libc++ version does not have this bug, and in general I can't provide support for libc++ or toolchain bugs. You're asking the wrong guy. All I know is that your toolchain is buggy.

**Comment by landryb** [comment]
looking at https://en.cppreference.com/w/cpp/compiler_support/20 many c++20 features landed in libcxx a long time ago (OpenBSD ships libcxx 16 iirc, there might be a work-in-progress update to 18), particularly in our case `std:invoke` in libcxx 12, so i'd be interested to know which exact bug we're talking about here :)

**Comment by MaxKellermann** [comment]
I have not tried to analyze the bug, and I don't feel that's worth my time, because it's not my problem.
The effect of this bug is that your toolchain fails to compile a valid piece of C++20 code. (So far, nobody has questioned that this code is valid C++20.)
