### ISSUE TITLE
Ncmpc sending empty queries do mopidy

### ISSUE THREAD

**Issue by opsxcq** [MusicPlayerDaemon/ncmpc#17]
When browsing my library (Artist List), the very first one is `<empty>`, so when I open that view, the user interface get stuck and I get the constant output in the status bar saying that the connection with the daemon has timed out.

I'm using mopidy as a daemon, and when this even happens, it spikes to 100% cpu, and get stuck there until I restart it or close ncmpc. Here is an interesting entry in the mopidy log

```
WARNING  A client or frontend made a library search with an empty query. This is strongly discouraged. Please check what sent this query and file a bug.
```

About my setup:

System: debian 9.2 kernel 4.9.0-6-amd64
ncmpcpp: 0.7.4

```
optional screens compiled-in:
 - tag editor
 - tiny tag editor
 - artist info
 - outputs
 - visualizer
 - clock
```

Let me know if you need any additional information

**Comment by MaxKellermann** [comment]
Using ncmpc with Mopidy is not supported.
But anyway, you're not using ncmpc, but "ncmpc**pp**" which is a completely different project with a very unfortunate name choice.

**Comment by opsxcq** [comment]
Thank you and sorry for the confusion !
