### ISSUE TITLE
Ctrl-W during search kills ncmpc if characters in the search field are cyrillic.

### ISSUE THREAD

**Issue by abominous** [MusicPlayerDaemon/ncmpc#18]
Example:

1. Enter search mode (5 -> 5)
2. Type ыыы 
3. Hit Ctrl-W
4. Program exits:
``Search:	ыыыncmpc: src/wreadln.c:355: wreadln_delete_char: Assertion `x < strlen(wr->line)' failed.
                                             Aborted``

Env:
1. ncmpc is 0.27
2. $LANG is en_US.utf8

**Comment by MaxKellermann** [comment]
Your ncmpc version is outdated.
