### ISSUE TITLE
Lyrics search kills ncmpc.

### ISSUE THREAD

**Issue by abominous** [MusicPlayerDaemon/ncmpc#19]
In 0.27, using lyrics search immediately exits the program:
``
ncmpc: src/plugin.c:174: plugin_data: Assertion `cycle->pid > 0' failed.
                   Aborted
``
I checked 0.24 and 0.25, and those do not have this problem - lyrics search works just as expected.

**Comment by MaxKellermann** [comment]
Your ncmpc version is outdated.
