### ISSUE TITLE
Exiting ncmpc messed up the terminal emulator.

### ISSUE THREAD

**Issue by abominous** [MusicPlayerDaemon/ncmpc#20]
Exiting ncmpc 0.27 causes the cursor in terminal emulator to disappear, scrollback to reset, mod keys to stop working and ncmpc appears to print ill-formatted core dump (until you type reset).
0.24 and 0.25 do not exhibit this problem.

ncmpc is 0.27
ncurses is 6.1-r2
shell is bash 4.4_p12
terminal emulator is xfce4-terminal is 0.8.7.2, built against vte 0.48.4

``
    /usr/lib64/libglib-2.0.so.0.5200.3
                                      7fdac814f000-7fdac8150000 r--p 00110000 08:03 411857                     /usr/lib64/libglib-2.0.so.0.5200.3
                                       7fdac8150000-7fdac8151000 rw-p 00111000 08:03 411857                     /usr/lib64/libglib-2.0.so.0.5200.3
                                        7fdac8151000-7fdac8152000 rw-p 00000000 00:00 0 
                                   7fdac8152000-7fdac8169000 r-xp 00000000 08:03 6693                       /usr/lib64/libmpdclient.so.2.0.10
                                   7fdac8169000-7fdac8368000 ---p 00017000 08:03 6693                       /usr/lib64/libmpdclient.so.2.0.10
                                   7fdac8368000-7fdac8369000 r--p 00016000 08:03 6693                       /usr/lib64/libmpdclient.so.2.0.10
                                   7fdac8369000-7fdac836a000 rw-p 00017000 08:03 6693                       /usr/lib64/libmpdclient.so.2.0.10
                                   7fdac836a000-7fdac83d4000 r-xp 00000000 08:03 1216681                    /lib64/libncursesw.so.6.1
                           7fdac83d4000-7fdac85d4000 ---p 0006a000 08:03 1216681                    /lib64/libncursesw.so.6.1
                   7fdac85d4000-7fdac85d8000 r--p 0006a000 08:03 1216681                    /lib64/libncursesw.so.6.1
           7fdac85d8000-7fdac85da000 rw-p 0006e000 08:03 1216681                    /lib64/libncursesw.so.6.1
   7fdac85da000-7fdac85fd000 r-xp 00000000 08:03 1313175                    /lib64/ld-2.25.so
                                        7fdac87c3000-7fdac87c8000 rw-p 00000000 00:00 0 
                                   7fdac87f2000-7fdac87f3000 rw-p 00000000 00:00 0 
                              7fdac87f3000-7fdac87fa000 r--s 00000000 08:03 3026772                    /usr/lib64/gconv/gconv-modules.cache
                                 7fdac87fa000-7fdac87fc000 rw-p 00000000 00:00 0 
                            7fdac87fc000-7fdac87fd000 r--p 00022000 08:03 1313175                    /lib64/ld-2.25.so
            7fdac87fd000-7fdac87fe000 rw-p 00023000 08:03 1313175                    /lib64/ld-2.25.so
                                                 7fdac87fe000-7fdac87ff000 rw-p 00000000 00:00 0 
                                            7ffd99d9c000-7ffd99dbd000 rw-p 00000000 00:00 0                          [stack]
                  7ffd99dfb000-7ffd99dfe000 r--p 00000000 00:00 0                          [vvar]
                                            7ffd99dfe000-7ffd99e00000 r-xp 00000000 00:00 0                          [vdso]
                 ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
                                               Aborted
``

**Comment by MaxKellermann** [comment]
Your ncmpc version is outdated.

**Comment by abominous** [comment]
Check again on 0.30 - this problem still happens.

**Comment by MaxKellermann** [comment]
Post a proper backtrace and I'll reopen this issue. (What you posted above is not one.)

**Comment by abominous** [comment]
```
(gdb) bt
#0  0x00007ffff6ec3f50 in raise () from /lib64/libc.so.6
#1  0x00007ffff6ec5bfa in abort () from /lib64/libc.so.6
#2  0x00007ffff6f06a00 in ?? () from /lib64/libc.so.6
#3  0x00007ffff6f0e66e in ?? () from /lib64/libc.so.6
#4  0x00007ffff6f0ef4e in ?? () from /lib64/libc.so.6
#5  0x00007ffff764f27c in mpd_settings_free () from /usr/lib64/libmpdclient.so.2
#6  0x00007ffff764786a in mpd_connection_free () from /usr/lib64/libmpdclient.so.2
#7  0x0000555555561f0b in mpdclient::Disconnect (this=0x7fffffffdba0)
    at ../src/mpdclient.cxx:270
#8  0x0000555555560926 in mpdclient::~mpdclient (this=0x7fffffffdba0, 
    __in_chrg=<optimized out>) at ../src/mpdclient.hxx:106
#9  0x000055555556089a in main (argc=1, argv=0x7fffffffdef8) at ../src/Main.cxx:384

```

**Comment by MaxKellermann** [comment]
Libmpdclient Version?

abominous <notifications@github.com> schrieb am Mo., 21. Mai 2018, 10:09:

**Comment by abominous** [comment]
> Libmpdclient Version?
2.10

bt full:
[gdb.txt](https://github.com/MusicPlayerDaemon/ncmpc/files/2021739/gdb.txt)

**Comment by MaxKellermann** [comment]
Neither 2.10 nor 2.9 are the latest version. This issue report stays closed.

**Comment by MaxKellermann** [comment]
These are minimum versions. You should always use the latest versions of everything. And your issue is not about ncmpc, but about libmpdclient (which you as a user admittedly could not know), therefore ncmpc's README.rst is irrelevant.
