### ISSUE TITLE
Lyrics search says "loading..." forever and never finishes.

### ISSUE THREAD

**Issue by abominous** [MusicPlayerDaemon/ncmpc#21]
Pressing 7 to search for lyrics searches forever and never returns result.

Using script manually (/usr/lib64/ncmpc/lyrics/20-lyricwiki.rb Artist Song) works though.

Ruby is installed.
ncmpc is 0.30

**Comment by MaxKellermann** [comment]
Can you see what the spawned child process is doing?

**Comment by MaxKellermann** [comment]
No reply
