### ISSUE TITLE
Various formatting improvements

### ISSUE THREAD

**Issue by squigglezworth** [MusicPlayerDaemon/ncmpc#31]
- Add a prefix option for both selected and unselected items
- Add an option to keep the screens list active permanently
    - Add color option for current screen
- Add option to format selected item 
- Improve configuration file comments to better illustrate what `color title` and `color title-bold` refer to (i.e., the former refers to the right-hand volume display and screen list names, and the latter the left-hand title)
    - On this topic, why do the screen list names use `color title` and the name prefixes use color title-bold? This seems randomly inconsistent to me. I'd recommend a setting for the screen list information and title, and a separate for the volume indicator

**Comment by MaxKellermann** [comment]
I'm unable to manage this ticket, because so many different things are mixed in here. Please write separate tickets for each issue. And explain what this "prefix" means.
