### ISSUE TITLE
Build warnings StatusBar.cxx and docs

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/ncmpc#32]
The Meson build system
Version: 0.47.1
Source dir: /data/src/ncmpc
Build dir: /data/src/ncmpc/output
Build type: native build
Project name: ncmpc
Project version: 0.31
Native C++ compiler: c++ (gcc 8.2.0 "c++ (Debian 8.2.0-4) 8.2.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Has header "locale.h": YES
Has header "libintl.h": YES
Checking for function "getaddrinfo" : YES
Found pkg-config: /usr/bin/pkg-config (0.29)
Native dependency ncursesw found: YES 6.1.20180714
Has header "ncursesw/curses.h": YES
Checking for function "getmouse" : YES
Dependency lirc found: NO
Dependency liblircclient0 found: NO
Compiler for C++ supports arguments -Wall: YES
Compiler for C++ supports arguments -Wextra: YES
Compiler for C++ supports arguments -Wno-deprecated-declarations -Wdeprecated-declarations: YES
Compiler for C++ supports arguments -Wshadow: YES
Compiler for C++ supports arguments -Wpointer-arith: YES
Compiler for C++ supports arguments -Wcast-qual: YES
Compiler for C++ supports arguments -Wcast-align: YES
Compiler for C++ supports arguments -Wwrite-strings: YES
Compiler for C++ supports arguments -Wmissing-declarations: YES
Compiler for C++ supports arguments -Wmissing-noreturn: YES
Compiler for C++ supports arguments -Wmissing-format-attribute: YES
Compiler for C++ supports arguments -Wredundant-decls: YES
Compiler for C++ supports arguments -Wundef: YES
Compiler for C++ supports arguments -Wno-non-virtual-dtor -Wnon-virtual-dtor: YES
Compiler for C++ supports arguments -fvisibility=hidden: YES
Compiler for C++ supports arguments -fno-exceptions: YES
Compiler for C++ supports arguments -fno-rtti: YES
Native dependency glib-2.0 found: YES 2.56.1
Native dependency libmpdclient found: YES 2.15
Configuring config.h using configuration
Program sphinx-build found: YES (/usr/bin/sphinx-build)
Build targets in project: 7
Found ninja-1.8.2 at /usr/bin/ninja
 
(...)

[14/62] Compiling C++ object 'ncmpc@exe/src_StatusBar.cxx.o'.
../src/StatusBar.cxx: In member function ‘void StatusBar::Update(const mpd_status*, const mpd_song*)’:
../src/StatusBar.cxx:151:6: warning: ‘%s’ directive output may be truncated writing up to 31 bytes into a region of size between 15 and 61 [-Wformat-truncation=]
      "%s [%s/%s]",
      ^~~~~~~~~~~~
      bitrate, elapsed_string, duration_string);
                               ~~~~~~~~~~~~~~~
../src/StatusBar.cxx:150:12: note: ‘snprintf’ output between 5 and 82 bytes into a destination of size 64
    snprintf(right_text, sizeof(right_text),
    ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      "%s [%s/%s]",
      ~~~~~~~~~~~~~
      bitrate, elapsed_string, duration_string);
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[61/62] Generating Manpage documentation with a custom command.
/data/src/ncmpc/doc/index.rst:211: WARNING: Inline interpreted text or phrase reference start-string without end-string.
[62/62] Generating HTML documentation with a custom command.
/data/src/ncmpc/doc/index.rst:211: WARNING: Inline interpreted text or phrase reference start-string without end-string.
WARNING: html_static_path entry u'/data/src/ncmpc/doc/_static' does not exist

**Comment by MaxKellermann** [comment]
6d31df3f0b44aac0cfbb552b66d4b282c867a93b
