### ISSUE TITLE
Keep screens list active at all times

### ISSUE THREAD

**Issue by squigglezworth** [MusicPlayerDaemon/ncmpc#34]
Per https://github.com/MusicPlayerDaemon/ncmpc/issues/31

Adding an option to allow keeping the screens list permanently active would be handy. As it is, it disappears after some time or an action.

**Comment by squigglezworth** [comment]
As well, allow a color setting for the current screen

**Comment by MaxKellermann** [comment]
Right now, the title bar is used for the screens list. Strictly following your words, I'd just disable the timer which replaces the screen list with the "regular" title bar. But is that what you want?

**Comment by squigglezworth** [comment]
That is, yes.

**Comment by MaxKellermann** [comment]
That way, you never see the mixer volume and the current path in the file browser.

**Comment by squigglezworth** [comment]
That's a fair point

Would it be a lot of work to implement a sort of second title bar, that way
we can display both the screens list as well as the information regularly
shown in the title bar?
