### ISSUE TITLE
Build error: default initialization of an object of const type 'const ScopeInitUTF8' without a user-provided default constructor

### ISSUE THREAD

**Issue by lbschenkel** [MusicPlayerDaemon/ncmpc#44]
Hi. I am the maintainer of `ncmpc` in MacPorts. I received a bug report from an user who could not build version 0.33 on MacOS 10.11 [1]:
```

info:build {
--
:info:build ^
:info:build  ../ncmpc-0.33/src/Main.cxx:293:22: error: default initialization of an  object of const type 'const ScopeInitUTF8' without a user-provided  default constructor
:info:build         const ScopeInitUTF8 init_utf8;
:info:build                             ^
:info:build                                      {}
:info:build 2 warnings and 1 error generated.
```
In this system, `locale_t` is not defined which results in an empty `ScopeInitUTF8` class, and apparently that triggers an error on old versions of clang that enforce a defect in the C++ standard, later corrected [3]. I could try introducing a patch downstream to work around that, but it would be even better if this could be addressed upstream?

[1] https://trac.macports.org/attachment/ticket/57996/main.log
[2] https://github.com/MusicPlayerDaemon/ncmpc/blob/c8bcf22cedd8c8d81ae8ba37da3789c15fb4421a/src/util/StringUTF8.hxx#L27
[3] https://stackoverflow.com/questions/7411515/why-does-c-require-a-user-provided-default-constructor-to-default-construct-a/47368753#47368753

**Comment by MaxKellermann** [comment]
So the defect is in the old standard and in the compiler being used, and not in the ncmpc source code, right?

**Comment by lbschenkel** [comment]
I believe so, yes, but I'm reporting this anyway because you might be interested in implementing a workaround for these old systems.

**Comment by MaxKellermann** [comment]
No, supporting known-buggy old systems is a bottomless pit. One should rather work towards pushing toolchain bug fixes to those users.

**Comment by lbschenkel** [comment]
All right, I'll patch it downstream then. Thanks.
