### ISSUE TITLE
Regression (0.25→0.26): Ignores password in $MPD_HOST on initial connect

### ISSUE THREAD

**Issue by wisq** [MusicPlayerDaemon/ncmpc#5]
With my `MPD_HOST` set to `passwerd@192.168.68.1`, ncmpc versions 0.26 and 0.27 can't connect to my MPD on my LAN server, but ncmpc 0.25 can.

Looking at the raw network traffic, I can see that 0.25 correctly sends a `password` command as the first command:

```
192.168.068.001.06600-192.168.068.003.52738: OK MPD 0.19.0

192.168.068.003.52738-192.168.068.001.06600: password "password"

192.168.068.001.06600-192.168.068.003.52738: OK

192.168.068.003.52738-192.168.068.001.06600: status

192.168.068.001.06600-192.168.068.003.52738: volume: -1
repeat: 0
random: 0
[etc]
```

But the issue is that 0.26 and 0.27 just try to launch straight into `status` and fail:

```
192.168.068.001.06600-192.168.068.003.52743: OK MPD 0.19.0

192.168.068.003.52743-192.168.068.001.06600: status

192.168.068.001.06600-192.168.068.003.52743: ACK [4@0] {status} you don't have permission for "status"
```

(I can't seem to compile the latest git so I can't see if it's fixed there.)

This originally happened on ncmpc installed via homebrew, but I've compiled the 0.25, 0.26, and 0.27 binaries directly from the GIthub releases to test them.  macOS Sierra, 10.12.6.

**Comment by MaxKellermann** [comment]
This was lost in commit 0ed117e41692a6ee764984e6855492e5945f7883 because the asynchronous code path ignores the password.
