### ISSUE TITLE
Starting a search results in high CPU usage

### ISSUE THREAD

**Issue by hiqua** [MusicPlayerDaemon/ncmpc#50]
Opening the search prompt (`5 5`) results in high cpu usage, which stops when the search ends (after pressing `Enter`).

The output of strace is similar to that described in https://github.com/MusicPlayerDaemon/ncmpc/issues/40#issue-377205448

[out.svg.txt](https://github.com/MusicPlayerDaemon/ncmpc/files/3038757/out.svg.txt)

Related: #40.

**Comment by MaxKellermann** [comment]
Your graph looks very different; please upload a strace. It might look similar to you, but tiny differences may give me some helpful hint where the cause is.

**Comment by MaxKellermann** [comment]
Oh, I don't need more data, I can reproduce the problem.
