### ISSUE TITLE
hscroll assertion basic.isDefined

### ISSUE THREAD

**Issue by joeyh** [MusicPlayerDaemon/ncmpc#51]
ncmpc: ../src/hscroll.cxx:69: void hscroll::Paint() const: Assertion `basic.IsDefined()' failed.

I can reliably get nmcpc to crash this way. I have a playlist containing two internet radio streams, which I load with mpc and start playing. Then ncmpd is started. Then, after about 1 second of playing the first stream, I down-arrow and Enter to switch to the other one, and it immediately crashes.

I guess this has to do with the ticker tape scrolling at the bottom of the screen. The first stream's url is displayed there at first, and is long enough it has to scroll. The second stream's url is shorter and does not need to scroll.

Versions: Both 0.33 and 0.35 have the problem.

**Comment by MaxKellermann** [comment]
I'm unable to reproduce this problem.
I have fixed a similar problem with commit c44784f7af609fd94b4fb0b7d23f329c671d51db, but this crash only occurred when the terminal was very narrow and there was no room at all for the song title. Even though I don't believe it fixes your problem, it is worth a try.
If the problem persists, please paste a backtrace.

**Comment by MaxKellermann** [comment]
Nevermind the reference in the commit - I used the wrong issue number.

But, is there any news on your issue?
