### ISSUE TITLE
Binding issues

### ISSUE THREAD

**Issue by concatime** [MusicPlayerDaemon/ncmpc#53]
Hi.
1. ~~I cannot bind the `'` character.~~ SOLVED with `0x27`
2. `Key l assigned to select-playing and down` warning.
3. The `screen-prev`/`screen-next` change only between `2: Queue` and `3: Browse`.

```
# .config/ncmpc/config
enable-mouse = yes

# .config/ncmpc/keys
key down = 'l'
key play = ';'
key go-parent-directory = 'j'
key screen-prev = 'J'
#key screen-next = '\'' DOES NOT WORK
key screen-next = 0x27
```

**Comment by MaxKellermann** [comment]
Please write separate bug reports for each issue you have. Mixing several issues in one bug report is confusing.
The warning (2.) comes from the default binding; by default, `l` is bound to `select-playing`. Your configuration doesn't change this, and so `l` is bound to two commands.

**Comment by MaxKellermann** [comment]
About 3.: screen-prev/next iterate only over the configured `screen-list`, which defaults to `playlist browse`. So the behavior you're seeing is correct.

**Comment by concatime** [comment]
Thank you, and I’m sorry for submitting multiple (pseudo-)issues.
Solutions for future readers:
2. `key select-playing = 0`
3. `screen-list = help playlist browse library search lyrics outputs song keydef`
