### ISSUE TITLE
How to bind Ctrl, Alt and Alt Right

### ISSUE THREAD

**Issue by concatime** [MusicPlayerDaemon/ncmpc#55]
I’ve searched in the documentation, but found noting beside https://github.com/MusicPlayerDaemon/ncmpc/blob/master/src/wreadln.cxx#L38

**Comment by MaxKellermann** [comment]
Those keys are modifiers and cannot be used by terminal programs. They can be combined with other keys, but not alone.

**Comment by MaxKellermann** [comment]
You can bind `Ctrl-A` or `Alt-A`.
But note that terminal programs are (by design) incapable of seeing a difference between `Alt-A` and `AltGr-A`. Both map to the same key code.

**Comment by concatime** [comment]
`Malformed hotkey definition: 'Alt-j'`
In my config, i have only `key screen-prev = 'Alt-j'`.

**Comment by MaxKellermann** [comment]
Indeed, the parser is broken.

**Comment by concatime** [comment]
New release pls?
