### ISSUE TITLE
Indicate whether random mode (etc.) is enabled

### ISSUE THREAD

**Issue by cole-miller** [MusicPlayerDaemon/ncmpc#57]
I was very confused recently when ncmpc started to play tracks from my queue in unpredictable order, until I guessed that I had accidentally hit `z`. A visual indication that random mode (or one of the other modes listed in the Help tab) is enabled would be very useful to avoid this sort of confusion.

**Comment by ferdnyc** [comment]
A view of the database details, ala `mpc stats`, would be cool as well.

Immediate thought, the Outputs page has a _lot_ of empty space on it, in most configs... 

(Obviously the repeat/random/single/consume indicators would be most useful somewhere on the static parts of the interface, though I expect they'd be single-character flags and thus rather cryptic. An expanded readout on one of the interface pages would probably be helpful for those, too.)

Other things it could theoretically host:
* Crossfade status
* Results of last DB update run

**Comment by cole-miller** [comment]
I think `[Random]` on the left end of the status line (just before or after `Playing`/`[Paused]` when a song is being displayed) would work well. And similarly for the other modes, of course.

**Comment by ferdnyc** [comment]
> ETA: a single-character indicator would have the advantage of taking up less space. Maybe `c`/`d`/`e`/`s` for consume/random/repeat/single?

That's what I was thinking, yeah, something along those lines... except, IIRC those switches aren't all mutually exclusive, right? Like, you can have MPD in consume-repeat-random mode.

So, I was actually thinking more along the lines of a `[----]` block, where any of the four hyphens could be replaced with a symbol (letter, punctuation, maybe even `1` for single) indicating the corresponding mode is enabled.

**Comment by ferdnyc** [comment]
That being said, given the space constraints, blocking off _six_ characters for relatively-infrequently-shown (for many users) mode indicators might be overkill, and it might be better to just show the _enabled_ mode letters, say between two colons.

e.g. MPD in repeat-single mode: **`:r1:`** When they're all disabled it's just a tiny **`::`**.

**Comment by ferdnyc** [comment]
Or, if ncmpc has all of Unicode to play in, random-repeat-single-consume could be: 🔀🔁🔂❎

But maybe that's losing sight of the purpose of a _text_ interface.

**Comment by MaxKellermann** [comment]
> A visual indication that random mode (or one of the other modes listed in the Help tab) is enabled would be very useful to avoid this sort of confusion.

I'm confused by this request. This exists already. As soon as you hit the `z` button, the text `[z]` appears at the top right corner of the screen, just below the volume level. Don't you see that?

> ETA: a single-character indicator would have the advantage of taking up less space. Maybe `c`/`d`/`e`/`s` for consume/random/repeat/single?

> So, I was actually thinking more along the lines of a `[----]` block

Something like this? https://github.com/MusicPlayerDaemon/ncmpc/blob/a80f88bd861b413f50909a3814d250ff1bc211ce/src/TitleBar.cxx#L60-L71

**Comment by MaxKellermann** [comment]
> Or, if ncmpc has all of Unicode to play in, random-repeat-single-consume could be: twisted_rightwards_arrowsrepeatrepeat_onenegative_squared_cross_mark

That's a nice idea, but the problem is that ncmpc has no way to check if the terminal's current font can display those characters. I tried experimenting with Unicode symbols recently, and found out that my own font doesn't.

**Comment by cole-miller** [comment]
> > A visual indication that random mode (or one of the other modes listed in the Help tab) is enabled would be very useful to avoid this sort of confusion.
> 
> I'm confused by this request. This exists already. As soon as you hit the `z` button, the text `[z]` appears at the top right corner of the screen, just below the volume level. Don't you see that?

I didn't until now! Thanks, I'll close the issue.

**Comment by ferdnyc** [comment]
> I didn't until now! Thanks, I'll close the issue.

Ditto, and I've figured out why. See, I normally have only crossfade enabled, which shows an 'x'. So, in the top of the window, I saw:
```
——————————————————————————————[x]—
```
...I honestly thought it was some sort of "window close button" affectation. :confounded: 

...Stop laughing at me.

**Comment by ferdnyc** [comment]
> A view of the database details, ala `mpc stats`, would be cool as well.

That, for the record, I have since noticed is also present. It's in the 'info' view, rather than on one of the permanent tabs.

Which works perfectly well, though it still seems like a lot of space is wasted in the Outputs tab.
