### ISSUE TITLE
"sh: turning off NDELAY mode" exit message under sh

### ISSUE THREAD

**Issue by parkmino** [MusicPlayerDaemon/ncmpc#59]
It is a little annoying to see this message every time ncmpc exits under sh.
Bash does not show this.

**Comment by MaxKellermann** [comment]
This bug appears to be about your POSIX shell, not about ncmpc.
If it were about ncmpc, you would have explained how it's related to ncmpc and you would have posted at least your ncmpc version number... wouldn't you?
