### ISSUE TITLE
Connection doesn't go through, no library shown

### ISSUE THREAD

**Issue by smangels** [MusicPlayerDaemon/ncmpc#62]
# Issue
When trying to connect to a Chord Poly (HighRes audio player) running MPD an error message is shown. I'm able to connect from an Android client (MAFA 1.2.9) without any issues. Unfortunately I'm not able to grab the version of the MPD service running on the Chord Poly.

# Error message

> wrong number of arguments for "tagtypes"

# ncmpc version information 
* no configuration files is used, they are non-existing
* running ArchLinux on kernel 5.4.13

```
ncmpc version: 0.36
build options: debug multibyte wide locale iconv nls colors lirc getmouse artist-screen help-screen search-screen song-screen key-screen lyrics-screen outputs-screen

configuration files:
 /home/s28131/.config/ncmpc/config
 /home/s28131/.ncmpc/config
 /etc/ncmpc/config
```
# Screenshot

![Screenshot from 2020-01-21 09-18-42](https://user-images.githubusercontent.com/4567226/72786881-039d6e80-3c2f-11ea-97d9-0bfb32117a46.png)

**Comment by MaxKellermann** [comment]
Which MPD version runs on this Chord Poly?
I have listed it on https://www.musicpd.org/commercial.html but the company has never contacted me, and I have no information about their product.
Please ask Chord Electronics for the the full source code of the MPD version they ship with their firmware. According to MPD's license, they must provide it to you, or else they violate my copyright.

**Comment by smangels** [comment]
I've written an email to the support and asked them kindly (in case they 
are using mpd) to register the proprietary device to the maintainer of the 
project and at the same time provide both source code and version number.
Thanks for taking care of this bug report.

Sent from my mobile device, please excuse my brevity.

Sebastian Mangelsen
Gothenburg, Sweden
+46707973573
sebastian@mangelsen.se
Den 21 januari 2020 12:21:20 skrev Max Kellermann <notifications@github.com>:

**Comment by MaxKellermann** [comment]
> to register the proprietary device to the maintainer

Side note: nobody needs to "register" with me. It's free software, they can just use (and sell) it without telling me. But they must obey the license conditions, which includes providing the source code.

What they also *must* do according to the license is to document MPD's license somewhere. So if they do ship MPD, but their user manual (or some other document which came with the product) doesn't have a copy of the license, they are violating my copyright already.

**Comment by smangels** [comment]
I understand. I've checked the available documentation. But there wasn't 
any license information regarding open source available. So I'll follow up 
with them regarding the source code used to provide the mpd service.

Sent from my mobile device, please excuse my brevity.

Sebastian Mangelsen
Gothenburg, Sweden
+46707973573
sebastian@mangelsen.se
Den 21 januari 2020 15:17:54 skrev Max Kellermann <notifications@github.com>:

**Comment by smangels** [comment]
update, using **ncmpcpp** I was able to connect to Chord Poly and the builtin MPD client, no warnings whatsoever

**Comment by MaxKellermann** [comment]
I know, and ncmpc 0.35 will work as well if my theory is correct. I believe the Chord Poly has a very old MPD version, and ncmpc 0.36 added an optimization which works only with newer MPD versions. I can fix that by adding a version check.

**Comment by smangels** [comment]
I have tested version 0.35 of ncmpc and can confirm that it works again. Yes, a version check seems to be a good idea. Thanks for the effort you've put into that bug report.

**Comment by MaxKellermann** [comment]
Did you get a reply from Chord already? I also sent them an email pointing out that they're violating my copyright, but got no reply so far.
Can you forward your email to me, please? (max@musicpd.org) ... because if they don't give you the full source code, all Chord products with MPD are automatically illegal and Chord loses the license to ever use MPD again. I bet they aren't aware how serious the situation is.

**Comment by smangels** [comment]
Hi, today I've manage to speak with their customer support and told them that they should get in contact with you as soon as possible. They couldn't put me through directly to some software responsible but they promised to follow-up on this ASAP.

**Comment by max-arnold** [comment]
Stumbled on the same issue on MacOS. Macports have outdated mpd version:

https://ports.macports.org/port/mpd/summary  0.20.23
https://ports.macports.org/port/ncmpc/summary   0.36
