### ISSUE TITLE
meson warning flags

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/ncmpc#63]
Warning messages on Debian testing x64

$ meson --buildtype=release -Ddocumentation=disabled . output
The Meson build system
Version: 0.52.1
Source dir: /data/src/ncmpc
Build dir: /data/src/ncmpc/output
Build type: native build
Project name: ncmpc
Project version: 0.38
C++ compiler for the host machine: c++ (gcc 10.0.1 "c++ (Debian 10-20200211-1) 10.0.1 20200211 (experimental)")
C++ linker for the host machine: GNU ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Has header "locale.h" : YES 
Has header "libintl.h" : YES 
Header <locale.h> has symbol "locale_t" : YES 
Checking for function "iconv" : YES 
Found pkg-config: /usr/bin/pkg-config (0.29)
Run-time dependency ncursesw found: YES 6.1.20191019
Has header "curses.h" with dependency ncursesw: YES 
Checking for function "getmouse" with dependency ncursesw: YES 
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency lirc found: NO (tried pkgconfig and cmake)
Compiler for C++ supports arguments -Wall: YES 
Compiler for C++ supports arguments -Wextra: YES 
Compiler for C++ supports arguments -Wno-deprecated-declarations -Wdeprecated-declarations: YES 
Compiler for C++ supports arguments -Wshadow: YES 
Compiler for C++ supports arguments -Wpointer-arith: YES 
Compiler for C++ supports arguments -Wcast-qual: YES 
Compiler for C++ supports arguments -Wcast-align: YES 
Compiler for C++ supports arguments -Wwrite-strings: YES 
Compiler for C++ supports arguments -Wmissing-declarations: YES 
Compiler for C++ supports arguments -Wmissing-noreturn: YES 
Compiler for C++ supports arguments -Wmissing-format-attribute: YES 
Compiler for C++ supports arguments -Wredundant-decls: YES 
Compiler for C++ supports arguments -Wundef: YES 
Compiler for C++ supports arguments -Wno-non-virtual-dtor -Wnon-virtual-dtor: YES 
Compiler for C++ supports arguments -fvisibility=hidden: YES 
Compiler for C++ supports arguments -Wno-format-truncation -Wformat-truncation: YES 
Compiler for C++ supports arguments -ffunction-sections: YES 
Compiler for C++ supports arguments -fdata-sections: YES 
WARNING: Consider using the builtin warning_level option instead of adding warning flags by hand.
WARNING: Consider using the builtin warning_level option instead of adding warning flags by hand.
Run-time dependency threads found: YES 
Run-time dependency Boost found: YES 1.71
Run-time dependency libmpdclient found: YES 2.19
Run-time dependency libpcre found: YES 8.39
Configuring config.h using configuration
Program sphinx-build skipped: feature documentation disabled
Build targets in project: 5
Found ninja-1.10.0 at /usr/bin/ninja

**Comment by MaxKellermann** [comment]
The exact meaning of Meson's `warning_level` is unspecified. There is no way to know which warnings will be enabled by a certain warning level or how to enable additional warnings. So we have to live with this Meson warning.
If you have a proper and stable solution, just say so.
