### ISSUE TITLE
Mac installation

### ISSUE THREAD

**Issue by Gahamelas** [MusicPlayerDaemon/ncmpc#68]
How does sone install this on mac terminal? I don't have apt.

**Comment by MaxKellermann** [comment]
https://github.com/MusicPlayerDaemon/ncmpc/blob/master/README.rst#how-to-compile-and-install-ncmpc
Or get it from Homebrew: https://formulae.brew.sh/formula/ncmpc

**Comment by Gahamelas** [comment]
How do I get it from homebrew? What would be the command? Thanks.

**Comment by Gahamelas** [comment]
I managed to install. Now I get the message: "Connection refused[1] " when executing the ncmpc.
