### ISSUE TITLE
Very strange sort in ncmpc

### ISSUE THREAD

**Issue by jas01** [MusicPlayerDaemon/ncmpc#69]
Hi,

Not sure it's a issue, but because I don't find any documentation about that...
When I go inside ncmpc in the browser section I'm totally unable to understand how the file are sorted. 
I check in the filesystem the name of the file are 'track_number - ' so through a «ls -l» it's correctly sorted.
I check the metadata for those file, the track number are correct.
But I've got something don't fit anything, not the title, not the tracknumber, not the file name sort.

And ncmpc does that only on ~ 30% of my folder.

**Comment by MaxKellermann** [comment]
ncmpc doesn't sort. It shows the files as they were received from MPD.
But MPD's database sorts directory entries. This is how:
https://github.com/MusicPlayerDaemon/MPD/blob/c6a7f6dabc3509bf0a11dc6eafa89aaa8125b86c/src/db/plugins/simple/SongSort.cxx#L79-L99
First by album name, then by disc number, then by tack number, then filename.
If you think something is wrong with that, submit a bug report to MPD and demonstrate what is wrong. In this bug report, you didn't name even one example - and you did not mention any version number!

**Comment by jas01** [comment]
> First by album name, then by disc number, then by tack number, then filename.




> First by album name, then by disc number, then by tack number, then filename.

In that case everything are fine. 

I just didn't know. 

Thanks for the super fast answer
