### ISSUE TITLE
Tab and Shift-Tab only bounce between screens 2 and 3

### ISSUE THREAD

**Issue by ferdnyc** [MusicPlayerDaemon/ncmpc#76]
Tested in the Fedora package builds of both 0.39 and 0.40 (not yet pushed to the repo), I noticed that even though <kbd>Tab</kbd> and <kbd>Shift</kbd>+<kbd>Tab</kbd> are documented as bound to "Next screen" and "Previous screen" (respectively), the only effect they actually seem to have is bouncing between screens 2 and 3.

From _any_ screen, if I hit <kbd>Tab</kbd> I end up on screen 2. Another <kbd>Tab</kbd> will take me to screen 3, then a third <kbd>Tab</kbd> puts me back on screen 2 again.

Going in the other direction, from _any_ screen <kbd>Shift</kbd>+<kbd>Tab</kbd> takes me to screen 3, another to screen 2, and then back to screen 3 again.

I even tried completely removing `$HOME/.config/ncmpc/config` to make sure it wasn't something messed up in my configs, but no change in the behavior.

**Comment by MaxKellermann** [comment]
Read the documentation about the `screen-list` setting here: https://www.musicpd.org/doc/ncmpc/html/#interface
The default value is `playlist browse`.
I admit that this is confusing - this is how this feature was designed 12 years ago by the original author... it makes some sense, but should be documented more clearly.
