### ISSUE TITLE
Double click actions for browsing through directories

### ISSUE THREAD

**Issue by mxmilkiib** [MusicPlayerDaemon/ncmpc#79]
I'm trying to use the mouse clicks to enter directories listed, but it appears it only very occasionally works, as in, I can click several times but I cannot predict the clicking pattern I must make to get going into a directory happen.

**Comment by MaxKellermann** [comment]
This probably depends on how your terminal emulator detects mouse clicks. There are several different events per mouse button:
- press
- release
- click
- double click
- triple click
A "click" is when you press and release very quickly, but the exact timings depend on your terminal emulator, and may be configurable. ncmpc cannot verify or change those timings - it only receives mouse events.

**Comment by mxmilkiib** [comment]
My default is urxvt, though I have just tried Termite, Xterm and Gnome Terminal.

I realise now that if I do a medium length (half second?) double click that mostly works to go into directories and back up.

I'm not sure how the ncmpcpp does it, but the shorter length between double clicks it can accept feels much more natural.

**Comment by MaxKellermann** [comment]
ncmpc doesn't handle double clicks, only single clicks.

**Comment by mxmilkiib** [comment]
I get it now. How about having double click open a directory, or to select a file and play it?

**Comment by MaxKellermann** [comment]
Yes, I implemented that yesterday: 7637e6f97bc380a1baef72ce20d6e78e2a4b668b
So I guess this is fixed now.
