### ISSUE TITLE
Need two "down a line" key to actually scroll down one line in help screen

### ISSUE THREAD

**Issue by OliverLew** [MusicPlayerDaemon/ncmpc#84]
As stated in the title. E.g. if I bind the "Move cursor down" or "scroll down one line" to <Down> arrow key, now I have to press <Down> twice to scroll down one line in Help screen.

I am not sure if others can reproduce. I can dig more if not.

Edit: The problem is actually only in scrolling down, not up.

**Comment by OliverLew** [comment]
I just did a git bisect, it pinpoint the issue to this commit:
```
$ git bisect bad
2a60a9f3937ddef6a1ed1f00871f5ea622e5faf3 is the first bad commit
commit 2a60a9f3937ddef6a1ed1f00871f5ea622e5faf3
Author: Max Kellermann <max@musicpd.org>
Date:   Mon Oct 5 16:14:30 2020 +0200

    ListCursor: clamp scroll_offset, replacing special case

    This replaces commit db6e2e0cb6880d687ce468093fe85d6ee26aa004, which
    caused a jumping cursor on song change when the whole queue was
    visible.

 NEWS               |  1 +
 src/ListCursor.cxx | 19 +++++++++++--------
 2 files changed, 12 insertions(+), 8 deletions(-)
```

**Comment by MaxKellermann** [comment]
I can't reproduce this. What is your ncmpc configuration? What is your terminal size? Does this happen only with some terminal sizes, or always?

**Comment by OliverLew** [comment]
I forgot to test with an empty configuration.
Just found that it only happens when `scroll-offset` is larger or equal to `$LINES - 4`, which is the number of lines excluding top 2 (tabs and separator) and bottom 2 (progress bar and status). So maybe you can try a larger value for this.
I am using version 0.43

**Comment by MaxKellermann** [comment]
That was a good hint - I can reproduce it now.
