### ISSUE TITLE
[Feature request] allow cancelling search

### ISSUE THREAD

**Issue by o-jasper** [MusicPlayerDaemon/ncmpc#85]
For instance escape to cancel searching.

**Comment by MaxKellermann** [comment]
What exactly should happen when you "cancel searching"?

**Comment by o-jasper** [comment]
State would go back to where you were before starting the search?

Basically the search bar going away is what would do that right now, afaik.

**Comment by MaxKellermann** [comment]
Ctrl-G (like most terminal-based applications).
