### ISSUE TITLE
Fails to retrieve lyrics with special characters in artist or track's name

### ISSUE THREAD

**Issue by diederikdehaas** [MusicPlayerDaemon/ncmpc#91]
I have a couple of tracks/albums by (Dutch) band `BLØF` and it fails to retrieve it's lyrics because azlyrics has 'translated' the `Ø` to `o`.
It does have them, see f.e.: https://www.azlyrics.com/lyrics/blof/demooisteverliezers.html

We actually don't (normally) have `Ø` in our alphabet, but other (Nordic?) countries likely do. Other languages like f.e. Spanish may have similar issues.

**Comment by MaxKellermann** [comment]
@astroanax fyi.

**Comment by diederikdehaas** [comment]
Thanks :)
