### ISSUE TITLE
Volume up not working

### ISSUE THREAD

**Issue by mckibbenc** [MusicPlayerDaemon/ncmpc#95]
The in-app volume up feature isn't working for either key ('+' or 'right'), but I can do volume down.  I'm using sndio, which recognizes mpd as an app and allows me to control the in-app volume up and down from sndioctl.  Here is my system:

OS: OpenBSD 6.8
Output: sndio
ncmpc version: 0.39

Here is the output from sndioctl:
```
user$ sndioctl
input.level=0.494
input.mute=0
output.level=0.498
output.mute=0
app/chrome0.level=1.000
app/mpd0.level=0.984
```

**Comment by MaxKellermann** [comment]
Why do you believe this is a ncmpc related problem and not MPD?

**Comment by mckibbenc** [comment]
My initial thought is that since the volume down keys ('-' or 'left') work in-app there might be something happening within ncmpc where it isn't recognizing the volume up or isn't able to communicate it properly to mpd.  I don't see any errors in /var/log/mpd/mpd.log.  Does ncmpc have a log or debug mode?  I could investigate further...

**Comment by jose1711** [comment]
MPD protocol is not encrypted hence you can debug very easily with e. g. `tcpdump`:
```shell
mpd_port=6600
tcpdump -Xi any dst port ${mpd_port}
```
You should see packets with payload like `setvol "78"` while setting the volume. Also you may try setting the volume using `telnet`.
```
{ echo 'setvol 100'; sleep 2; } | telnet ${mpd_host} ${mpd_port}
```

**Comment by mckibbenc** [comment]
I ran the tcpdump and confirmed that ncmpc is not sending a setvol command on volume up, only on volume down.  I tried setting the volume using mpc, and I found that trying to increment the volume up by 1 resulted in no change in the volume, and no setvol command was sent to mpd.

```text
pc$ mpc volume +1 
Interpol - PDA
[playing] #3/11   0:04/5:35 (1%)
volume: 70%   repeat: off   random: off   single: off   consume: off
pc$ mpc volume +1 
Interpol - PDA
[playing] #3/11   0:06/5:35 (1%)
volume: 70%   repeat: off   random: off   single: off   consume: off
```

However, incrementing the volume by 2 will actually increase the volume by 1 percent, and the setvol will be sent to mpd.

```text
pc$ mpc volume +2 
Interpol - PDA
[playing] #3/11   0:54/5:35 (16%)
volume: 71%   repeat: off   random: off   single: off   consume: off
pc$ mpc volume +2 
Interpol - PDA
[playing] #3/11   0:55/5:35 (16%)
volume: 72%   repeat: off   random: off   single: off   consume: off
```

**Comment by MaxKellermann** [comment]
This really looks like a rounding error, and this rounding error is in MPD (or in the hardware mixer driver). If this still occurs with the latest MPD version, report it over there.

**Comment by vext01** [comment]
I have the same issue, also on OpenBSD: pressing - or left changes volume downwards, but + or right does nothing.

However, you can increase the volume if you hold down + or right. Oddly this workaround only works when I run ncmpc on a remote host.

I don't know if this is related, but I can change the volume using `mpc` but it's always 1% less than requested:
```
toastrack$ mpc vol 60
Scandroid - Aphelion
[playing] #1/14496   1:47/5:35 (31%)
volume: 59%   repeat: off   random: off   single: off   consume: off
toastrack$ mpc vol 61
Scandroid - Aphelion
[playing] #1/14496   1:49/5:35 (32%)
volume: 60%   repeat: off   random: off   single: off   consume: off
toastrack$ mpc vol 62
Scandroid - Aphelion
[playing] #1/14496   1:50/5:35 (32%)
volume: 61%   repeat: off   random: off   single: off   consume: off
```

Perhaps when you press + ncmpc asks mpd what the current volume level is and increments it, but if so that becomes a no-op.
