### ISSUE TITLE
«Page» doesn't show

### ISSUE THREAD

**Issue by jas01** [MusicPlayerDaemon/ncmpc#98]
Hi

When this config 
```
library-page-tags = composer album performer conductor artist date
```
If for a composer who just have one album, the «page» are not show we jump after select “one_album_composer” directly to the «performer» page.

Don't know if it's a bug or a feature, but for classical music it's not very convenient.

Version ncmpc 
```
ncmpc version: 0.45
build options: debug multibyte wide locale iconv nls colors lirc getmouse artist-screen help-screen search-screen song-screen key-screen lyrics-screen outputs-screen chat-screen
```

Version mpd 
```
Music Player Daemon 0.22.8 (0.22.8)
```

**Comment by MaxKellermann** [comment]
It's a feature. It would be pointless to ask the user to select an album if there is only one, so ncmpc omits that one.
